/*
Sawvant Cutting Optimization API

REST API for 2D guillotine sheet cutting optimization. Submit optimization jobs, poll for status, or stream progress via SSE. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sawvant

import (
	"encoding/json"
)

// checks if the Margins type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Margins{}

// Margins struct for Margins
type Margins struct {
	// mm trim per side
	Top *float64 `json:"top,omitempty"`
	Bottom *float64 `json:"bottom,omitempty"`
	Left *float64 `json:"left,omitempty"`
	Right *float64 `json:"right,omitempty"`
}

// NewMargins instantiates a new Margins object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMargins() *Margins {
	this := Margins{}
	var top float64 = 0
	this.Top = &top
	var bottom float64 = 0
	this.Bottom = &bottom
	var left float64 = 0
	this.Left = &left
	var right float64 = 0
	this.Right = &right
	return &this
}

// NewMarginsWithDefaults instantiates a new Margins object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarginsWithDefaults() *Margins {
	this := Margins{}
	var top float64 = 0
	this.Top = &top
	var bottom float64 = 0
	this.Bottom = &bottom
	var left float64 = 0
	this.Left = &left
	var right float64 = 0
	this.Right = &right
	return &this
}

// GetTop returns the Top field value if set, zero value otherwise.
func (o *Margins) GetTop() float64 {
	if o == nil || IsNil(o.Top) {
		var ret float64
		return ret
	}
	return *o.Top
}

// GetTopOk returns a tuple with the Top field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Margins) GetTopOk() (*float64, bool) {
	if o == nil || IsNil(o.Top) {
		return nil, false
	}
	return o.Top, true
}

// HasTop returns a boolean if a field has been set.
func (o *Margins) HasTop() bool {
	if o != nil && !IsNil(o.Top) {
		return true
	}

	return false
}

// SetTop gets a reference to the given float64 and assigns it to the Top field.
func (o *Margins) SetTop(v float64) {
	o.Top = &v
}

// GetBottom returns the Bottom field value if set, zero value otherwise.
func (o *Margins) GetBottom() float64 {
	if o == nil || IsNil(o.Bottom) {
		var ret float64
		return ret
	}
	return *o.Bottom
}

// GetBottomOk returns a tuple with the Bottom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Margins) GetBottomOk() (*float64, bool) {
	if o == nil || IsNil(o.Bottom) {
		return nil, false
	}
	return o.Bottom, true
}

// HasBottom returns a boolean if a field has been set.
func (o *Margins) HasBottom() bool {
	if o != nil && !IsNil(o.Bottom) {
		return true
	}

	return false
}

// SetBottom gets a reference to the given float64 and assigns it to the Bottom field.
func (o *Margins) SetBottom(v float64) {
	o.Bottom = &v
}

// GetLeft returns the Left field value if set, zero value otherwise.
func (o *Margins) GetLeft() float64 {
	if o == nil || IsNil(o.Left) {
		var ret float64
		return ret
	}
	return *o.Left
}

// GetLeftOk returns a tuple with the Left field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Margins) GetLeftOk() (*float64, bool) {
	if o == nil || IsNil(o.Left) {
		return nil, false
	}
	return o.Left, true
}

// HasLeft returns a boolean if a field has been set.
func (o *Margins) HasLeft() bool {
	if o != nil && !IsNil(o.Left) {
		return true
	}

	return false
}

// SetLeft gets a reference to the given float64 and assigns it to the Left field.
func (o *Margins) SetLeft(v float64) {
	o.Left = &v
}

// GetRight returns the Right field value if set, zero value otherwise.
func (o *Margins) GetRight() float64 {
	if o == nil || IsNil(o.Right) {
		var ret float64
		return ret
	}
	return *o.Right
}

// GetRightOk returns a tuple with the Right field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Margins) GetRightOk() (*float64, bool) {
	if o == nil || IsNil(o.Right) {
		return nil, false
	}
	return o.Right, true
}

// HasRight returns a boolean if a field has been set.
func (o *Margins) HasRight() bool {
	if o != nil && !IsNil(o.Right) {
		return true
	}

	return false
}

// SetRight gets a reference to the given float64 and assigns it to the Right field.
func (o *Margins) SetRight(v float64) {
	o.Right = &v
}

func (o Margins) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Margins) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Top) {
		toSerialize["top"] = o.Top
	}
	if !IsNil(o.Bottom) {
		toSerialize["bottom"] = o.Bottom
	}
	if !IsNil(o.Left) {
		toSerialize["left"] = o.Left
	}
	if !IsNil(o.Right) {
		toSerialize["right"] = o.Right
	}
	return toSerialize, nil
}

type NullableMargins struct {
	value *Margins
	isSet bool
}

func (v NullableMargins) Get() *Margins {
	return v.value
}

func (v *NullableMargins) Set(val *Margins) {
	v.value = val
	v.isSet = true
}

func (v NullableMargins) IsSet() bool {
	return v.isSet
}

func (v *NullableMargins) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMargins(val *Margins) *NullableMargins {
	return &NullableMargins{value: val, isSet: true}
}

func (v NullableMargins) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMargins) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


