/*
Sawvant Cutting Optimization API

REST API for 2D guillotine sheet cutting optimization. Submit optimization jobs, poll for status, or stream progress via SSE. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sawvant

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RateLimitError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitError{}

// RateLimitError struct for RateLimitError
type RateLimitError struct {
	Error string `json:"error"`
	// Request limit for this tier and strategy (24h sliding window)
	Limit int32 `json:"limit"`
	// Remaining requests in the current window
	Remaining int32 `json:"remaining"`
	// Which strategy quota was exceeded
	Strategy string `json:"strategy"`
}

type _RateLimitError RateLimitError

// NewRateLimitError instantiates a new RateLimitError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitError(error_ string, limit int32, remaining int32, strategy string) *RateLimitError {
	this := RateLimitError{}
	this.Error = error_
	this.Limit = limit
	this.Remaining = remaining
	this.Strategy = strategy
	return &this
}

// NewRateLimitErrorWithDefaults instantiates a new RateLimitError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitErrorWithDefaults() *RateLimitError {
	this := RateLimitError{}
	return &this
}

// GetError returns the Error field value
func (o *RateLimitError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *RateLimitError) SetError(v string) {
	o.Error = v
}

// GetLimit returns the Limit field value
func (o *RateLimitError) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *RateLimitError) SetLimit(v int32) {
	o.Limit = v
}

// GetRemaining returns the Remaining field value
func (o *RateLimitError) GetRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remaining, true
}

// SetRemaining sets field value
func (o *RateLimitError) SetRemaining(v int32) {
	o.Remaining = v
}

// GetStrategy returns the Strategy field value
func (o *RateLimitError) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *RateLimitError) SetStrategy(v string) {
	o.Strategy = v
}

func (o RateLimitError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["limit"] = o.Limit
	toSerialize["remaining"] = o.Remaining
	toSerialize["strategy"] = o.Strategy
	return toSerialize, nil
}

func (o *RateLimitError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"limit",
		"remaining",
		"strategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRateLimitError := _RateLimitError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRateLimitError)

	if err != nil {
		return err
	}

	*o = RateLimitError(varRateLimitError)

	return err
}

type NullableRateLimitError struct {
	value *RateLimitError
	isSet bool
}

func (v NullableRateLimitError) Get() *RateLimitError {
	return v.value
}

func (v *NullableRateLimitError) Set(val *RateLimitError) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitError) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitError(val *RateLimitError) *NullableRateLimitError {
	return &NullableRateLimitError{value: val, isSet: true}
}

func (v NullableRateLimitError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


