/*
Sawvant Cutting Optimization API

REST API for 2D guillotine sheet cutting optimization. Submit optimization jobs, poll for status, or stream progress via SSE. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sawvant

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Placement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Placement{}

// Placement struct for Placement
type Placement struct {
	PartId string `json:"part_id"`
	// Which sheet type this part is placed on
	SheetId string `json:"sheet_id"`
	// mm from top-left of usable area
	X float64 `json:"x"`
	// mm from top-left of usable area
	Y float64 `json:"y"`
	// Post-edge-banding dimension
	Width float64 `json:"width"`
	// Post-edge-banding dimension
	Height float64 `json:"height"`
	Rotated bool `json:"rotated"`
	Grain GrainDirection `json:"grain"`
}

type _Placement Placement

// NewPlacement instantiates a new Placement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlacement(partId string, sheetId string, x float64, y float64, width float64, height float64, rotated bool, grain GrainDirection) *Placement {
	this := Placement{}
	this.PartId = partId
	this.SheetId = sheetId
	this.X = x
	this.Y = y
	this.Width = width
	this.Height = height
	this.Rotated = rotated
	this.Grain = grain
	return &this
}

// NewPlacementWithDefaults instantiates a new Placement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlacementWithDefaults() *Placement {
	this := Placement{}
	return &this
}

// GetPartId returns the PartId field value
func (o *Placement) GetPartId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value
// and a boolean to check if the value has been set.
func (o *Placement) GetPartIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartId, true
}

// SetPartId sets field value
func (o *Placement) SetPartId(v string) {
	o.PartId = v
}

// GetSheetId returns the SheetId field value
func (o *Placement) GetSheetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SheetId
}

// GetSheetIdOk returns a tuple with the SheetId field value
// and a boolean to check if the value has been set.
func (o *Placement) GetSheetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SheetId, true
}

// SetSheetId sets field value
func (o *Placement) SetSheetId(v string) {
	o.SheetId = v
}

// GetX returns the X field value
func (o *Placement) GetX() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *Placement) GetXOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *Placement) SetX(v float64) {
	o.X = v
}

// GetY returns the Y field value
func (o *Placement) GetY() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *Placement) GetYOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *Placement) SetY(v float64) {
	o.Y = v
}

// GetWidth returns the Width field value
func (o *Placement) GetWidth() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *Placement) GetWidthOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *Placement) SetWidth(v float64) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *Placement) GetHeight() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *Placement) GetHeightOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *Placement) SetHeight(v float64) {
	o.Height = v
}

// GetRotated returns the Rotated field value
func (o *Placement) GetRotated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Rotated
}

// GetRotatedOk returns a tuple with the Rotated field value
// and a boolean to check if the value has been set.
func (o *Placement) GetRotatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rotated, true
}

// SetRotated sets field value
func (o *Placement) SetRotated(v bool) {
	o.Rotated = v
}

// GetGrain returns the Grain field value
func (o *Placement) GetGrain() GrainDirection {
	if o == nil {
		var ret GrainDirection
		return ret
	}

	return o.Grain
}

// GetGrainOk returns a tuple with the Grain field value
// and a boolean to check if the value has been set.
func (o *Placement) GetGrainOk() (*GrainDirection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grain, true
}

// SetGrain sets field value
func (o *Placement) SetGrain(v GrainDirection) {
	o.Grain = v
}

func (o Placement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Placement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["part_id"] = o.PartId
	toSerialize["sheet_id"] = o.SheetId
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	toSerialize["rotated"] = o.Rotated
	toSerialize["grain"] = o.Grain
	return toSerialize, nil
}

func (o *Placement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"part_id",
		"sheet_id",
		"x",
		"y",
		"width",
		"height",
		"rotated",
		"grain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlacement := _Placement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlacement)

	if err != nil {
		return err
	}

	*o = Placement(varPlacement)

	return err
}

type NullablePlacement struct {
	value *Placement
	isSet bool
}

func (v NullablePlacement) Get() *Placement {
	return v.value
}

func (v *NullablePlacement) Set(val *Placement) {
	v.value = val
	v.isSet = true
}

func (v NullablePlacement) IsSet() bool {
	return v.isSet
}

func (v *NullablePlacement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlacement(val *Placement) *NullablePlacement {
	return &NullablePlacement{value: val, isSet: true}
}

func (v NullablePlacement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlacement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


