/*
Sawvant Cutting Optimization API

REST API for 2D guillotine sheet cutting optimization. Submit optimization jobs, poll for status, or stream progress via SSE. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sawvant

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Metrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Metrics{}

// Metrics struct for Metrics
type Metrics struct {
	// Total cut length in mm
	TotalCutLength float64 `json:"total_cut_length"`
	TotalCuts int32 `json:"total_cuts"`
	TotalRotations int32 `json:"total_rotations"`
	TotalStacks int32 `json:"total_stacks"`
	CutCycles int32 `json:"cut_cycles"`
}

type _Metrics Metrics

// NewMetrics instantiates a new Metrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetrics(totalCutLength float64, totalCuts int32, totalRotations int32, totalStacks int32, cutCycles int32) *Metrics {
	this := Metrics{}
	this.TotalCutLength = totalCutLength
	this.TotalCuts = totalCuts
	this.TotalRotations = totalRotations
	this.TotalStacks = totalStacks
	this.CutCycles = cutCycles
	return &this
}

// NewMetricsWithDefaults instantiates a new Metrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsWithDefaults() *Metrics {
	this := Metrics{}
	return &this
}

// GetTotalCutLength returns the TotalCutLength field value
func (o *Metrics) GetTotalCutLength() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCutLength
}

// GetTotalCutLengthOk returns a tuple with the TotalCutLength field value
// and a boolean to check if the value has been set.
func (o *Metrics) GetTotalCutLengthOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCutLength, true
}

// SetTotalCutLength sets field value
func (o *Metrics) SetTotalCutLength(v float64) {
	o.TotalCutLength = v
}

// GetTotalCuts returns the TotalCuts field value
func (o *Metrics) GetTotalCuts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCuts
}

// GetTotalCutsOk returns a tuple with the TotalCuts field value
// and a boolean to check if the value has been set.
func (o *Metrics) GetTotalCutsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCuts, true
}

// SetTotalCuts sets field value
func (o *Metrics) SetTotalCuts(v int32) {
	o.TotalCuts = v
}

// GetTotalRotations returns the TotalRotations field value
func (o *Metrics) GetTotalRotations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalRotations
}

// GetTotalRotationsOk returns a tuple with the TotalRotations field value
// and a boolean to check if the value has been set.
func (o *Metrics) GetTotalRotationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRotations, true
}

// SetTotalRotations sets field value
func (o *Metrics) SetTotalRotations(v int32) {
	o.TotalRotations = v
}

// GetTotalStacks returns the TotalStacks field value
func (o *Metrics) GetTotalStacks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalStacks
}

// GetTotalStacksOk returns a tuple with the TotalStacks field value
// and a boolean to check if the value has been set.
func (o *Metrics) GetTotalStacksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalStacks, true
}

// SetTotalStacks sets field value
func (o *Metrics) SetTotalStacks(v int32) {
	o.TotalStacks = v
}

// GetCutCycles returns the CutCycles field value
func (o *Metrics) GetCutCycles() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CutCycles
}

// GetCutCyclesOk returns a tuple with the CutCycles field value
// and a boolean to check if the value has been set.
func (o *Metrics) GetCutCyclesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CutCycles, true
}

// SetCutCycles sets field value
func (o *Metrics) SetCutCycles(v int32) {
	o.CutCycles = v
}

func (o Metrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Metrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_cut_length"] = o.TotalCutLength
	toSerialize["total_cuts"] = o.TotalCuts
	toSerialize["total_rotations"] = o.TotalRotations
	toSerialize["total_stacks"] = o.TotalStacks
	toSerialize["cut_cycles"] = o.CutCycles
	return toSerialize, nil
}

func (o *Metrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_cut_length",
		"total_cuts",
		"total_rotations",
		"total_stacks",
		"cut_cycles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetrics := _Metrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetrics)

	if err != nil {
		return err
	}

	*o = Metrics(varMetrics)

	return err
}

type NullableMetrics struct {
	value *Metrics
	isSet bool
}

func (v NullableMetrics) Get() *Metrics {
	return v.value
}

func (v *NullableMetrics) Set(val *Metrics) {
	v.value = val
	v.isSet = true
}

func (v NullableMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetrics(val *Metrics) *NullableMetrics {
	return &NullableMetrics{value: val, isSet: true}
}

func (v NullableMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


