/*
Sawvant Cutting Optimization API

REST API for 2D guillotine sheet cutting optimization. Submit optimization jobs, poll for status, or stream progress via SSE. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sawvant

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Summary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Summary{}

// Summary struct for Summary
type Summary struct {
	TotalSheets int32 `json:"total_sheets"`
	YieldPercent float64 `json:"yield_percent"`
	WastePercent float64 `json:"waste_percent"`
	// mm²
	WasteArea float64 `json:"waste_area"`
	UnplacedParts []string `json:"unplaced_parts,omitempty"`
	SheetsUsed []SheetUsage `json:"sheets_used"`
}

type _Summary Summary

// NewSummary instantiates a new Summary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummary(totalSheets int32, yieldPercent float64, wastePercent float64, wasteArea float64, sheetsUsed []SheetUsage) *Summary {
	this := Summary{}
	this.TotalSheets = totalSheets
	this.YieldPercent = yieldPercent
	this.WastePercent = wastePercent
	this.WasteArea = wasteArea
	this.SheetsUsed = sheetsUsed
	return &this
}

// NewSummaryWithDefaults instantiates a new Summary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryWithDefaults() *Summary {
	this := Summary{}
	return &this
}

// GetTotalSheets returns the TotalSheets field value
func (o *Summary) GetTotalSheets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalSheets
}

// GetTotalSheetsOk returns a tuple with the TotalSheets field value
// and a boolean to check if the value has been set.
func (o *Summary) GetTotalSheetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSheets, true
}

// SetTotalSheets sets field value
func (o *Summary) SetTotalSheets(v int32) {
	o.TotalSheets = v
}

// GetYieldPercent returns the YieldPercent field value
func (o *Summary) GetYieldPercent() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.YieldPercent
}

// GetYieldPercentOk returns a tuple with the YieldPercent field value
// and a boolean to check if the value has been set.
func (o *Summary) GetYieldPercentOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.YieldPercent, true
}

// SetYieldPercent sets field value
func (o *Summary) SetYieldPercent(v float64) {
	o.YieldPercent = v
}

// GetWastePercent returns the WastePercent field value
func (o *Summary) GetWastePercent() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.WastePercent
}

// GetWastePercentOk returns a tuple with the WastePercent field value
// and a boolean to check if the value has been set.
func (o *Summary) GetWastePercentOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WastePercent, true
}

// SetWastePercent sets field value
func (o *Summary) SetWastePercent(v float64) {
	o.WastePercent = v
}

// GetWasteArea returns the WasteArea field value
func (o *Summary) GetWasteArea() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.WasteArea
}

// GetWasteAreaOk returns a tuple with the WasteArea field value
// and a boolean to check if the value has been set.
func (o *Summary) GetWasteAreaOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WasteArea, true
}

// SetWasteArea sets field value
func (o *Summary) SetWasteArea(v float64) {
	o.WasteArea = v
}

// GetUnplacedParts returns the UnplacedParts field value if set, zero value otherwise.
func (o *Summary) GetUnplacedParts() []string {
	if o == nil || IsNil(o.UnplacedParts) {
		var ret []string
		return ret
	}
	return o.UnplacedParts
}

// GetUnplacedPartsOk returns a tuple with the UnplacedParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetUnplacedPartsOk() ([]string, bool) {
	if o == nil || IsNil(o.UnplacedParts) {
		return nil, false
	}
	return o.UnplacedParts, true
}

// HasUnplacedParts returns a boolean if a field has been set.
func (o *Summary) HasUnplacedParts() bool {
	if o != nil && !IsNil(o.UnplacedParts) {
		return true
	}

	return false
}

// SetUnplacedParts gets a reference to the given []string and assigns it to the UnplacedParts field.
func (o *Summary) SetUnplacedParts(v []string) {
	o.UnplacedParts = v
}

// GetSheetsUsed returns the SheetsUsed field value
func (o *Summary) GetSheetsUsed() []SheetUsage {
	if o == nil {
		var ret []SheetUsage
		return ret
	}

	return o.SheetsUsed
}

// GetSheetsUsedOk returns a tuple with the SheetsUsed field value
// and a boolean to check if the value has been set.
func (o *Summary) GetSheetsUsedOk() ([]SheetUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.SheetsUsed, true
}

// SetSheetsUsed sets field value
func (o *Summary) SetSheetsUsed(v []SheetUsage) {
	o.SheetsUsed = v
}

func (o Summary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Summary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_sheets"] = o.TotalSheets
	toSerialize["yield_percent"] = o.YieldPercent
	toSerialize["waste_percent"] = o.WastePercent
	toSerialize["waste_area"] = o.WasteArea
	if !IsNil(o.UnplacedParts) {
		toSerialize["unplaced_parts"] = o.UnplacedParts
	}
	toSerialize["sheets_used"] = o.SheetsUsed
	return toSerialize, nil
}

func (o *Summary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_sheets",
		"yield_percent",
		"waste_percent",
		"waste_area",
		"sheets_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummary := _Summary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSummary)

	if err != nil {
		return err
	}

	*o = Summary(varSummary)

	return err
}

type NullableSummary struct {
	value *Summary
	isSet bool
}

func (v NullableSummary) Get() *Summary {
	return v.value
}

func (v *NullableSummary) Set(val *Summary) {
	v.value = val
	v.isSet = true
}

func (v NullableSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummary(val *Summary) *NullableSummary {
	return &NullableSummary{value: val, isSet: true}
}

func (v NullableSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


